version: "3.9"  # optional since v1.27.0
services:
  mq:
    container_name: mq   
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword      
    ports:
      - 15672:15672
      - 5672:5672

